#!/bin/sh

echo "1" > /proc/sys/net/ipv4/icmp_echo_ignore_broadcasts
echo "0" > /proc/sys/net/ipv4/conf/all/accept_source_route
echo "0" > /proc/sys/net/ipv4/conf/all/accept_redirects
echo "1" > /proc/sys/net/ipv4/icmp_ignore_bogus_error_responses
echo "1" > /proc/sys/net/ipv4/tcp_syncookies

iptables -A INPUT  -p icmp -m state --state ESTABLISHED,RELATED     -j ACCEPT
iptables -A INPUT  -m state --state ESTABLISHED                     -j ACCEPT
iptables -A OUTPUT -p icmp -m state --state NEW,ESTABLISHED,RELATED -j ACCEPT
iptables -A OUTPUT -m state --state NEW,ESTABLISHED                 -j ACCEPT

## Allow Local Traffic
iptables -A INPUT -i eth1 -j ACCEPT

## allow loop back traffic (localhost)
iptables -A INPUT -i lo -j ACCEPT


## allow wireguard traffic
iptables -A INPUT -i wg0 -j ACCEPT
iptables -A INPUT -d 192.174.24.104 -p udp --dport 52813 -j ACCEPT

## Allow Ryan to ssh in (the host name rule is being delayed to avoid race issues #
#iptables -A INPUT -s ghost.btfh.net -d 192.174.24.104 -p tcp --dport 22 -j ACCEPT
iptables -A INPUT -s 129.82.0.0/16  -d 192.174.24.104 -p tcp --dport 22 -j ACCEPT

## allow some icmp traffic and block the rest
iptables -A INPUT -p icmp --icmp-type 0 -j ACCEPT
iptables -A INPUT -p icmp --icmp-type 8 -j ACCEPT
iptables -A INPUT -p icmp -j DROP

# Block all incoming traffic (excluding port forwards )
iptables -A INPUT -i ppp0    -j DROP
iptables -A INPUT -i eth0:4  -j DROP
iptables -A INPUT -i eth0:5  -j DROP
iptables -A INPUT -i eth0:6  -j DROP
iptables -A INPUT -i eth0:7  -j DROP
iptables -A INPUT -i eth0:8  -j DROP
iptables -A INPUT -i eth0:9  -j DROP
iptables -A INPUT -i eth0:10 -j DROP
